gazebo:
  ros__parameters:
    publish_rate: 500.0

controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_controller:
      type: mecanum_drive_controller/MecanumDriveController

mecanum_controller:
  ros__parameters:
    front_left_wheel_name: wheel_front_left_joint
    front_right_wheel_name: wheel_front_right_joint
    rear_left_wheel_name: wheel_rear_left_joint
    rear_right_wheel_name: wheel_rear_right_joint
    wheel_radius: 0.07
    wheel_separation_width: 0.3
    wheel_separation_length: 0.5
    use_stamped_vel: false
    base_frame_id: base_link
    cmd_vel_timeout: 0.5
    publish_rate: 50.0
