ros__parameters:
    controller_manager:
        update_rate: 50

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        mecanum_controller:
            type: mecanum_drive_controller/MecanumDriveController

    mecanum_controller:
        type: mecanum_drive_controller/MecanumDriveController
        left_front_wheel_name: wheel_front_left_joint
        right_front_wheel_name: wheel_front_right_joint
        left_rear_wheel_name: wheel_rear_left_joint
        right_rear_wheel_name: wheel_rear_right_joint

        wheel_radius: 0.07
        wheel_separation_width: 0.3
        wheel_separation_length: 0.4
        publish_rate: 50
        cmd_vel_timeout: 0.25
        enable_odom_tf: true
        use_stamped_vel: false

